### ISSUE TITLE
[BUG]:  The call throws an error

### ISSUE THREAD

**Issue by AndreiMoraru123** [naimo84/github-readme-stats-calculate-rank#1]
**Description**
Unexpected token "export"

**To Reproduce**
!npx github-readme-stats-calculate-rank@latest --totalRepos 25 --totalCommits 1800 --contributions 11 --followers 16 --prs 16 --issues 51 --stargazers 127

**or** 

!npm install -g github-readme-stats-calculate-rank
!github-readme-stats-calculate-rank --totalRepos 25 --totalCommits 1800 --contributions 11 --followers 16 --prs 16 --issues 51 --stargazers 127

**Expected behavior**
output should be: { level: 'A++', score: 44.902066802062436 }

**Screenshots**
![image](https://user-images.githubusercontent.com/81184255/206864849-d6de530d-af4c-4cbf-a40e-ef5ec14c4280.png)
![image](https://user-images.githubusercontent.com/81184255/206864874-a44ccd6d-36ed-41a3-8690-8612d3476224.png)

**Additional context**
Tested both locally and on Google Colab

**Comment by naimo84** [comment]
HEy @AndreiMoraru123, 

should be fixed with 1.0.4. I didn't realize, that the calculate.js from anuraghazra's repo changed from commonjs to esm ;) https://github.com/anuraghazra/github-readme-stats/commit/107f7ca52c3431bf989e7c3624ad130e98cb4f5a

Greets,
Benjamin
